packages:
- '.'
flags:
  pandoc:
    embed_data_files: true
extra-deps:
- HDBC-sqlite3-2.3.3.1
- gridtables-0.1.0.0
- hslua-cli-1.2.0
- hslua-list-1.1.0.1
- hslua-module-zip-1.0.0
- jira-wiki-markup-1.5.0
- mime-types-0.1.1.0
- doctemplates-0.11
- texmath-0.12.6
- citeproc-0.8.1
- pandoc-types-1.23
- pandoc-lua-marshal-0.2.0
- commonmark-pandoc-0.2.1.3
- pandoc-3.0.1
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-20.6
