# Welcome

Here's our website. Have a look around.

Our last two events:

$recentevents:event()$

For a complete list of events, see the [events](events.html) page.

yst supports unicode:

- ὕαλον ϕαγεῖν δύναμαι· τοῦτο οὔ με βλάπτει.
- أنا قادر على أكل الزجاج و هذا لا يؤلمني.
- 我能吞下玻璃而不伤身体。


yst code inclusion:

~~~~ {.haskell include="includeCode.hs"}
-- This should be a code block
main = putStrLn "Hello!"
~~~~
