\\documentclass{article}
\\usepackage{amsmath}
\\usepackage[mathletters]{ucs}
\\usepackage[utf8x]{inputenc}
\\usepackage{hyperref}
\\usepackage{listings}

\\lstnewenvironment{code}{\\lstset{language=Haskell,basicstyle=\\small\\ttfamily}}{}

\\setlength{\\parindent}{0pt}
\\setlength{\\parskip}{6pt plus 2pt minus 1pt}

\\title{$pagetitle$}

\\begin{document}
\\maketitle

$contents$

\\end{document}
