<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>$sitetitle$ - $pagetitle$</title>
  <meta name="viewport" content="width=device-width">
  <link href="$root$bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="$root$css/screen.css">
  <link rel="stylesheet" media="print" href="$root$css/print.css">
  <script src="js/modernizr-2.6.2.min.js"></script>
</head>
<body>
    <!--[if lt IE 7]>
        <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
    <![endif]-->
    <div class="row-fluid">
      <div id="nav" class="span2">
$nav$
      </div>
      <div id="maincol" class="span10">
$contents$
      </div>
    </div>
    <script src="js/jquery-1.8.2.min.js"></script>
    <script src="js/nav.js"></script>
    <script src="$root$bootstrap/js/bootstrap.min.js"></script>
</body>
</html>
