<html>
<head>
   <title>$sitetitle$ - $pagetitle$</title>
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
   <link rel="stylesheet" type="text/css" href="$root$css/screen.css" />
   <link rel="stylesheet" type="text/css" media="print" href="$root$css/print.css" />
   <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js" type="text/javascript"></script>
   <script src="$root$js/nav.js" type="text/javascript"></script>
</head>
<body>
  <div id="doc3" class="yui-t1">
    <div id="yui-main">
      <div id="maincol" class="yui-b">
$contents$
      </div>
    </div>
    <div id="nav" class="yui-b first">
$nav$
    </div>
  </div>
</body>
</html>
